### ISSUE TITLE
Question re: use_Xresources and use_iTerm_colors options

### ISSUE THREAD

**Issue by colepeters** [kristijanhusak/vim-hybrid-material#11]
I’m curious about the `g:hybrid_use_Xresources` and `g:hybrid_use_iTerm_colors` options in the theme. Because of some strange colours appearing in a different plugin which doesn’t use `gui` colours, I decided to check which `cterm` colours were being used via the Hybrid Material theme; for example:

```
:hi linenr
LineNr         xxx ctermfg=11 guifg=#455A64
```

When I looked into the Hybrid Material colours configuration, I found that `LineNr` was using `s:yellow` as its colour, which in turn was being evaluated to `ctermfg=11`. However, looking into the code, it should only be set to this colour if `g:hybrid_use_Xresources == 1` ([as specified on these lines](https://github.com/kristijanhusak/vim-hybrid-material/blob/master/colors/hybrid_material.vim#L121-L128)).

I haven’t myself set either the `Xresources` or `iTerm_colours` options, and if I’m reading the code correctly, the colour scheme should be [setting those both to a default of `0`](https://github.com/kristijanhusak/vim-hybrid-material/blob/master/colors/hybrid_material.vim#L60-L66).

When I tried explicitly setting both of these options to `0`, I still got `ctermfg=11` coming back for `:hi LineNr`.

It seems to me that [the colours being set outside of these conditionals](https://github.com/kristijanhusak/vim-hybrid-material/blob/master/colors/hybrid_material.vim#L150-L160) are using a nicer 256-colour palette, but I just can't seem to get the colour scheme to make use of them.

Any advice as to how I might get this configured properly?
(Apologies if I’ve missed something obvious; reading Vimscript has never been my strong suit.) ;)

**Comment by kristijanhusak** [comment]
Do you need to change `LineNr` or `CursorLineNr` color ?
I'm not sure if you are checking proper highlighting. `LineNr` is default color of a line number (should be grayish), and `CursorLineNr` is current line number color (This one should be yellow). Can you recheck with `:hi CursorLineNr` ?

**Comment by colepeters** [comment]
@kristijanhusak Here’s the output from both:

```
:hi LineNr
LineNr         xxx ctermfg=11 guifg=#455A64
```
```
:hi CursorLineNr
CursorLineNr   xxx ctermfg=11 gui=bold guifg=#f0c674
```

So, it looks like both of these are returning `ctermfg=11`, which I believe is bright yellow.

**Comment by kristijanhusak** [comment]
@colepeters 
That is really strange, because there is no any situation where LineNr could have ctermfg=11.

It's set [here](https://github.com/kristijanhusak/vim-hybrid-material/blob/master/colors/hybrid_material.vim#L315)

It uses `s:fg_selection` which is set [here](https://github.com/kristijanhusak/vim-hybrid-material/blob/master/colors/hybrid_material.vim#L207)

`fg_selection` uses `s_selection` which is set:

* [here](https://github.com/kristijanhusak/vim-hybrid-material/blob/master/colors/hybrid_material.vim#L88) for GUI
* [here](https://github.com/kristijanhusak/vim-hybrid-material/blob/master/colors/hybrid_material.vim#L123) for Xresources
* [here](https://github.com/kristijanhusak/vim-hybrid-material/blob/master/colors/hybrid_material.vim#L136) for iTerm colors 
* and [here](https://github.com/kristijanhusak/vim-hybrid-material/blob/master/colors/hybrid_material.vim#L151) for regular terminal (xterm)

None of those have value of 11. 

There is one `qfLineNr` highligthing group [here](https://github.com/kristijanhusak/vim-hybrid-material/blob/master/colors/hybrid_material.vim#L400) which is for quickfix window, but that should not interfere with regular `LineNr`.

Can you try disabling all other plugins and test again? Maybe some of those change the values.

**Comment by colepeters** [comment]
@kristijanhusak Stranger and stranger.

Here’s a screenshot of the output of the previous two commands, with all other plugins (except vim-plug) disabled (still `ctermfg=11`):

![Output of `:hi LineNr`](https://cloud.githubusercontent.com/assets/1713932/14570952/b114c4c4-033e-11e6-9655-69e79e0585d3.png)

![Output of `:hi CursorLineNr`](https://cloud.githubusercontent.com/assets/1713932/14570964/bb58d47a-033e-11e6-952a-21117b4cba8f.png)

And here’s where I see `LineNr`’s rendering as yellow:

![image](https://cloud.githubusercontent.com/assets/1713932/14570993/e3975600-033e-11e6-92fe-316e437df6c3.png)

The above shows the `:Lines` command from [FZF.vim](https://github.com/junegunn/fzf.vim). It uses the `ctermfg` from the active Vim colour scheme for `LineNr` for the numbers you’re seeing in yellow (see [this issue I opened with FZF.vim’s maintainer](https://github.com/junegunn/fzf.vim/issues/112) for further details).

On other colour schemes, I don’t seem to have this issue (but I’d like to keep using hybrid-material). Not sure if any of this helps?

**Comment by kristijanhusak** [comment]
I didn't know you were using true color variable.
As FZF maintaner explained, cterm colors are never set for you because gui is detected (because of true color).

I unified the schemes so it sets up both cterm and gui colors at same time. Check the [develop](https://github.com/kristijanhusak/vim-hybrid-material/tree/develop) branch. Pull it down, and try using that one and see what happens. Also, if you notice any other differences, please let me know.

**Comment by colepeters** [comment]
Ah, apologies! I totally forgot to mention that I was using true colour.
Using the develop branch, FZF `:Lines` output now looks like this:

![image](https://cloud.githubusercontent.com/assets/1713932/14580503/b0ad31be-03c6-11e6-9db0-0751e5f13108.png)

…which accurately reflect the theme’s cterm colours (though the background keeps using the true colour background swatch). However, I can probably modify the colours being picked from the theme by FZF in my config, so I think this should be fine.

Thanks for your help on this!

**Comment by kristijanhusak** [comment]
Ok great. Everything else looks ok? I'm planning to merge develop to master, and i want to make sure everything is fine on iTerm.

**Comment by colepeters** [comment]
Just opened a bunch of assorted HTML/JS/JSX/CSS files (with true colour enabled, in Neovim, which is running in iTerm), and everything about the colour scheme looks as expected. So it seems fine to me! :)

**Comment by kristijanhusak** [comment]
Great, thanks! :)
