### ISSUE TITLE
Tag colors not matching with .js .jsx

### ISSUE THREAD

**Issue by Blake-LeBlanc** [kristijanhusak/vim-hybrid-material#22]
Hello Kristijan! 

While editing .js and .jsx files, I noticed that some of the tag colors do not match, as noted in the attached screenshot.

- Is there anything you need me to try on my end? 

- Any more information I can submit?

Thank you so much for your excellent color theme, hybrid_reverse is such a great theme to code with :)

![text57](https://user-images.githubusercontent.com/19244245/42377812-8923350a-80ea-11e8-8a59-5c9bd5572bc4.png)

**Comment by kristijanhusak** [comment]
How is it working in regular html?

**Comment by Blake-LeBlanc** [comment]
The opening tag is yellow and closing tag is red.

To be honest with you, I never noticed the mismatch until I started working with Javascript. Is this how it's intended to be Kristijan?

![image](https://user-images.githubusercontent.com/19244245/42413051-54de4ede-81de-11e8-9753-4a38a37c98a7.png)

**Comment by kristijanhusak** [comment]
I checked this, and it looks like the opening and closing tag are not using the same highlight group.
So for opening tag it's this:
`hi<xmlTagName> trans<xmlTagName> lo<Function>`
And for closing it's this:
`hi<xmlEndTag> trans<xmlEndTag> lo<Identifier>`

So opening tag is using Function hi group, where closing is using Identifier hi group.
Gruvbox have this covered because they added custom highlights for `xmlTagName` and `xmlEndTag` hi groups. Here it just fallbacks to Function/Identifier.

So this is not on purpose, but in my opinion, this is even better, because it helps distinguishing the opening and closing tags more easily.

**Comment by Blake-LeBlanc** [comment]
Thank you Kristijan for looking into this so quickly!

I agree there's some value in being able to easily distinguish between opening and closed tags. 

Sounds good to me!

All the best,
Blake
