### ISSUE TITLE
Airline theme details in screenshot

### ISSUE THREAD

**Issue by jrolfs** [kristijanhusak/vim-hybrid-material#9]
I'm curious how you achieved a few details in your screenshot:
  - Small airline arrow separators
  - No arrow separators for buffers/tabs
  - Icon in selected buffer/tab

Your screenshot (annotated):
![yours](http://d.pr/i/1i77e+))

Here's a screenshot of my current setup:
![mine](http://d.pr/i/1hri2+)

**Comment by jrolfs** [comment]
Also, what font are you using in the screenshot? Thanks!

**Comment by kristijanhusak** [comment]
You can find all in my vimfiles https://github.com/kristijanhusak/vimfiles
There is a font which i'm using named `Inconsolata for Powerline Plus Nerd File Types.otf`. It has that arrows for airline, and those icons for file types. Check vimrc for packages and setup used.

**Comment by jrolfs** [comment]
Wow, I should have dug a little further into your repos for your dotfiles :disappointed:

That's an awesome `vimrc` you have there. I switched from `Inconsolata` (after using it for a long time) to `Source Code Pro` but I may have to check it out again. I've recently been trying out Vimfiler, do I have to use NERDTree to have all the file type icons work in Airline?

Thanks!

**Comment by kristijanhusak** [comment]
Check plugin that handles that https://github.com/ryanoasis/vim-devicons

As it says in description, it supports Vimfiler, you just need proper font that i mentioned in the comment above.

**Comment by jrolfs** [comment]
Thank you for your help :)

**Comment by PezCoder** [comment]
hey @kristijanhusak,  I checked your vim files.. & Since i'm using vim in iterm2 I followed your base-16 instructions to put the correct colors in place. 
I'm using `Inconsolata for Powerline Plus Nerd File Types.otf` + vim-devicons.
I'm not getting those details due to some reasons here's my vimrc stuff related to this theme:

```
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

set background=dark
let base16colorspace=256
colorscheme base16-material

let g:airline_powerline_fonts = 1                                               "Enable powerline fonts
let g:airline_theme = "hybrid"                                                  "Set theme to powerline default theme
let g:airline_section_y = '%{substitute(getcwd(), expand("$HOME"), "~", "g")}'  "Set relative path
let g:airline#extensions#whitespace#enabled = 0                                 "Disable whitespace extension
let g:airline#extensions#tabline#enabled = 1                                    "Enable tabline extension
let g:airline#extensions#tabline#left_sep = ' '                                 "Left separator for tabline
let g:airline#extensions#tabline#left_alt_sep = '│'                             "Right separator for tabline

```

Points to note: 
1. I have manually downloaded the base16-material version provide by you for vim terminal users & installed the same on my iterm2. No issue in colors (It looks just great !)
2. I'm assuming that `let g:airline_theme = "hybrid" ` < this hybrid theme is coming from airline-themes.
3. The icons are working fine.

How can i get the perfect boxes & arrow as mentioned by @jrolfs for top & bottom bar of airline?

Here's the screenshot of my current system: (Mac OSX, iterm2, VIM)
![image](https://cloud.githubusercontent.com/assets/8057916/18931277/1eb7d020-85e9-11e6-8112-ecd0a8e7c999.png)
